# .gitlab-ci.yml
stages: [build, test, release, publish]

default:
  image: maven:3.9.9-eclipse-temurin-23
  cache:
    key: maven-repo
    paths:
      - .m2/repository
  before_script:
    - java -version
    - mvn -v

build:
  stage: build
  script:
    - mvn -B -q -DskipTests package

test:
  stage: test
  artifacts:
    when: always
    paths:
      - target/surefire-reports/
    expire_in: 1 week
    rules:
      - if: '$CI_COMMIT_BRANCH == "main"'
        when: manual
      - when: never
  variables:
    # keep GPG files isolated (optional, nice for debugging)
    GNUPGHOME: "$CI_PROJECT_DIR/.gnupg"
  before_script:
    # 1) Import armored, base64-encoded private key from CI var
    - mkdir -p "$GNUPGHOME"
    - echo "$GPG_PRIVATE_KEY_ARMOR" | base64 -d > /tmp/private.key
    - gpg --batch --import /tmp/private.key
    - rm -f /tmp/private.key

    # 2) Non-interactive pinentry so Maven can pass the passphrase
    - echo "pinentry-mode loopback" >> "$GNUPGHOME/gpg.conf"
    - echo "allow-loopback-pinentry" >> "$GNUPGHOME/gpg-agent.conf"

    # 3) (Optional) show that the key is present (prints only key IDs)
    - gpg --list-secret-keys --keyid-format LONG

    # If you know the exact key ID/fingerprint, export it for Maven:
    # - export GPG_KEYID=YOURKEYIDHERE
  script:
    # Run your signed build/deploy; do NOT pass passphrase on CLI
    # maven-gpg-plugin will pick up MAVEN_GPG_PASSPHRASE from env
    - mvn -B -e q -s .mvn/settings.xml -DtrimStackTrace=false verify

release:
  stage: release
  image: node:20
  needs: ["test"]
  variables:
    GIT_DEPTH: "0"    # full history + tags for semantic-release
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual     # show Play button; do not auto-run
      allow_failure: false
    - when: never      # hide on all other branches/sources
  before_script:
    - npm -v
    - npm i -g semantic-release @semantic-release/{gitlab,git,exec,changelog,commit-analyzer,release-notes-generator}
  script:
    - semantic-release

publish:
  stage: publish
  image: maven:3.9.9-eclipse-temurin-23
  needs: [ "release" ]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
    - when: never
  before_script:
    # Import private key from CI variable
    - echo "$GPG_PRIVATE_KEY_ARMOR" | base64 -d > /tmp/private.key
    - gpg --batch --import /tmp/private.key
    - rm -f /tmp/private.key
    # Non-interactive gpg setup
    - mkdir -p ~/.gnupg
    - echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
    - echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
    - export GPG_TTY=$(tty)
  script:
    # Use your Maven settings that contain Sonatype 'central' credentials
    - mvn -B -q -s .mvn/settings.xml -Dgpg.passphrase="$GPG_PASSPHRASE" deploy
